language: java

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "YOUR GIT USER NAME"
      - git config --local user.email "YOUR GIT USER EMAIL"
      - git tag "bbbbbbbbbbb"

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  skip_cleanup: true
  on:
    tags: false
