language: java

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "YOUR GIT USER NAME"
      - git config --local user.email "YOUR GIT USER EMAIL"
      - git tag "Version: $(date +'%Y')"

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
  - Dockerfile
  - pom.xml
  skip_cleanup: true
  on:
    tags: false
